In [27]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import math
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from collections import defaultdict
import re

In [28]:
training_data = pd.read_csv('/content/drive/MyDrive/DM Assignment 2/DataMining Aiignment 2/train_data.csv')
testing_data = pd.read_csv('/content/drive/MyDrive/DM Assignment 2/DataMining Aiignment 2/test_data.csv')

In [29]:
training_data.head()

,Unnamed: 0,Sentence_id,New_Sentence,Type
0,0,GERRES15609,Author and/or Review architecture/design and o...,Responsibility
1,1,PHERES15784,Should be able to develop custom dynamic shape...,Responsibility
2,2,GERREQ10457,Experience in working crosslly with a larger ...,Requirement
3,3,GERSKL27235,"Previous business experience, including but no...",Skill
4,4,HONSSK18415,Delivering fast and right the first time.,SoftSkill

In [30]:
testing_data.head()

   Unnamed: 0  Sentence_id                                       New_Sentence
0           0  UAERES16346  Collaborate across all of DB&T practices and o...
1           1  COGREQ15586  Strong  technology expertise in Identity and A...
2           2  UAEREQ12722       Strong knowledge on Service  Virtualization.
3           3  COGSKL29155  Architect scalable data processing and analyti...
4           4  PHERES12551  Map client organization, build outstanding rel...

In [48]:
def remove_tags(string):
    removelist = ""
    result = re.sub('','',string)          #remove HTML tags
    result = re.sub('https://.*','',result)   #remove URLs
    result = re.sub(r'[^w'+removelist+']', ' ',result)    #remove non-alphanumeric characters 
    result = result.lower()
    return result
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
training_data['New_Sentence'] = training_data['New_Sentence'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (stop_words)]))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [49]:
import nltk
nltk.download('omw-1.4')
w_tokenizer = nltk.tokenize.WhitespaceTokenizer()
lemmatizer = nltk.stem.WordNetLemmatizer()
def lemmatize_text(text):
  st = ""
  for w in w_tokenizer.tokenize(text):
    st = st + lemmatizer.lemmatize(w) + " "
  return st
training_data['New_Sentence'] = training_data.New_Sentence.apply(lemmatize_text)

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [50]:
training_data

,Unnamed: 0,Sentence_id,New_Sentence,Type
0,0,GERRES15609,Authorand/orReviewarchitecture/designtechnical...,Responsibility
1,1,PHERES15784,"Shouldabledevelopcustomdynamicshape,objectscri...",Responsibility
2,2,GERREQ10457,ExperienceworkingcrossllylargerEngineeringOrga...,Requirement
3,3,GERSKL27235,"Previousbusinessexperience,includinglimitedbus...",Skill
4,4,HONSSK18415,Deliveringfastrightfirsttime.,SoftSkill
...,...,...,...,...
60110,60110,UAERES18030,"Inposition,utilizeprogrammanagementskillsdrive...",Responsibility
60111,60111,GERRES3026,"Inaddition,individualresponsiblemanaging1small...",Responsibility
60112,60112,INDSSK5492,Goodproblemsolvingskills.,SoftSkill
60113,60113,PHESSK15092,GoodExcelknowledge.,SoftSkill
60114,60114,HONEDU1643,"BachelorsDegreeElectricalEngineering,Mechanica...",Education

In [55]:
from sklearn.preprocessing import LabelEncoder
New_Sentence = training_data['New_Sentence'].values
labels = training_data['Type'].values
encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(labels)

In [57]:
encoded_labels

array([3, 3, 2, ..., 5, 5, 0])

In [58]:
train_sentences, test_sentences, train_labels, test_labels = train_test_split(New_Sentence , encoded_labels, stratify = encoded_labels)

In [60]:
from collections import defaultdict

In [61]:
vec = CountVectorizer(max_features = 3000)
X = vec.fit_transform(train_sentences)
vocab = vec.get_feature_names()
X = X.toarray()
word_counts = {}
for l in range(2):
    word_counts[l] = defaultdict(lambda: 0)
for i in range(X.shape[0]):
    l = train_labels[i]
    for j in range(len(vocab)):
        word_counts[l][vocab[j]] += X[i][j]

KeyError: ignored